### ISSUE TITLE
lscand output log needs to have identifier field

### ISSUE THREAD

**Issue by takutolehr** [BayshoreNetworks/gargoyle#4]
Currently, lscand outputs the following into syslog:
`gargoyle_lscand_bruteforce: action="block" violator="192.168.101.101" detection_type="51" timestamp="1516829885"
`

As you can see there is no way for one to tell which config triggered the block. Maybe lscand can insert the filename of the config in the log as config="configfile", or make a new property in the config file to use it as an identifier.

**Comment by dre** [comment]
This has been pushed into the develop branch and will be in v 1.6.4
